project:
  type: book

book:
  title: "WebQuest: Criptografía RSA"
  author: "Alejandro Muñoz Azaustre"
  language: es

  chapters:
    - part: "Introducción"
      chapters:
        - index.qmd
        - webquest-rsa/tarea.qmd
        - webquest-rsa/proceso.qmd
    - part: "Construye tu criptosistema RSA"
      chapters:
        - webquest-rsa/teoria.qmd
        - webquest-rsa/intro-python.qmd
        - webquest-rsa/primos.qmd
        - webquest-rsa/playground.qmd
    - part: "Cierre"
      chapters:
      - webquest-rsa/evaluacion.qmd
      - webquest-rsa/conclusion.qmd
      - webquest-rsa/creditos.qmd
    - part: "Guía Docente"
      chapters: 
        - webquest-rsa/docente.qmd

format:
  pdf:
    latex-tinytex: false
    standalone: false
    pdf-engine: xelatex
    documentclass: book
    fontsize: 12pt
    include-in-header:
      - assets/latex/preambulo.tex
      - assets/latex/ce-lengths.tex
      - assets/latex/tablas.tex
    template-partials:
      - assets/latex/before-body.tex

lang: es