project:
  type: website
  output-dir: docs

website:
  title: "Webquest: Criptografía RSA (2º ESO)"
  navbar:
    background: primary
    foreground: light
    right:
      - icon: github
        href: https://github.com/LordAlex93
        aria-label: GitHub

    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Tarea"
        href: webquest-rsa/tarea.qmd
      - text: "Proceso"
        href: webquest-rsa/proceso.qmd
      - text: "Construye tu criptosistema RSA"
        menu:
          - text: "¿Qué es la criptografía?"
            href: webquest-rsa/teoria.qmd
          - text: "Introducción a Python"
            href: webquest-rsa/intro-python.qmd
          - text: "Primos y Python"
            href: webquest-rsa/primos.qmd
          - text: "Programa tu criptosistema"
            href: webquest-rsa/playground.qmd
      - text: "Evaluación"
        href: webquest-rsa/evaluacion.qmd
      - text: "Conclusión"
        href: webquest-rsa/conclusion.qmd

      - text: "Créditos"
        href: webquest-rsa/creditos.qmd
      - text: "Guía Docente"
        href: webquest-rsa/docente.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "Contenidos"
    toc-depth: 3
    code-fold: false
    code-tools: false
  pdf:
    title-block: true        # Asegura que el PDF muestre la portada/título del YAML
    latex-tinytex: true
lang: es

execute:
  echo: true
